steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/rails-test-image', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', 'gcr.io/$PROJECT_ID/rails-test-image', 'bundle', 'exec', 'rails', 'test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', 'gcr.io/$PROJECT_ID/rails-test-image', 'bundle', 'exec', 'rake', 'assets:precompile']
    env: ['S3_KEY=something','S3_SECRET=something','RAILS_ENV=production']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['replace', '-f', 'rails_replication_controller.yaml']
    env: ['CLOUDSDK_COMPUTE_ZONE=us-central1-c','CLOUDSDK_CONTAINER_CLUSTER=scott-cluster']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply','-f','rails_service.yaml']
    env: ['CLOUDSDK_COMPUTE_ZONE=us-central1-c','CLOUDSDK_CONTAINER_CLUSTER=scott-cluster']
images:
  - 'gcr.io/$PROJECT_ID/rails-test-image'
