kind: Service
apiVersion: v1
metadata:
  name: railsapp-service
spec:
  selector:
    app: railsapp
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080