apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: railsapp-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: railsapp
    spec:
      containers:
      - name: railsapp
        image: gcr.io/scott-demo-project/rails-test-image
        ports:
        - containerPort: 8080
        env:
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: railsapp-secrets
                key: secret-key-base